// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_container_registry_auth

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ContainerRegistryAuthResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"container_registry_auth_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of container registry auth to return.",
				MarkdownDescription: "ID of container registry auth to return.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A unique string identifying a container registry authentication.",
				MarkdownDescription: "A unique string identifying a container registry authentication.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A user-defined name for a container registry authentication. The name must be unique.",
				MarkdownDescription: "A user-defined name for a container registry authentication. The name must be unique.",
			},
			"password": schema.StringAttribute{
				Required:            true,
				Description:         "The password for the container registry.",
				MarkdownDescription: "The password for the container registry.",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "The username for the container registry.",
				MarkdownDescription: "The username for the container registry.",
			},
		},
	}
}

type ContainerRegistryAuthModel struct {
	ContainerRegistryAuthId types.String `tfsdk:"container_registry_auth_id"`
	Id                      types.String `tfsdk:"id"`
	Name                    types.String `tfsdk:"name"`
	Password                types.String `tfsdk:"password"`
	Username                types.String `tfsdk:"username"`
}
