// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_network_volume

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkVolumeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data_center_id": schema.StringAttribute{
				Required:            true,
				Description:         "The RunPod data center ID where the created network volume is located.",
				MarkdownDescription: "The RunPod data center ID where the created network volume is located.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "A unique string identifying a network volume.",
				MarkdownDescription: "A unique string identifying a network volume.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A user-defined name for the created network volume. The name does not need to be unique.",
				MarkdownDescription: "A user-defined name for the created network volume. The name does not need to be unique.",
			},
			"network_volume_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of network volume to return.",
				MarkdownDescription: "ID of network volume to return.",
			},
			"size": schema.Int64Attribute{
				Required:            true,
				Description:         "The amount of disk space, in gigabytes (GB), allocated to the created network volume.",
				MarkdownDescription: "The amount of disk space, in gigabytes (GB), allocated to the created network volume.",
				Validators: []validator.Int64{
					int64validator.Between(0, 4000),
				},
			},
		},
	}
}

type NetworkVolumeModel struct {
	DataCenterId    types.String `tfsdk:"data_center_id"`
	Id              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	NetworkVolumeId types.String `tfsdk:"network_volume_id"`
	Size            types.Int64  `tfsdk:"size"`
}
