// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_runpod

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func RunpodProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type RunpodModel struct {
}
